[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kamino_predict = "radCWLzDo2E2LnEqdY8H8mitLfzSzAVNGfzHyX2foe5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
