[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kamino_predict = "BJizs7CKAsLec1RWp8W3hJG1TPnLZ2aLsNboToWYs5BC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
